### ISSUE TITLE
Error Material Dialog

### ISSUE THREAD

**Issue by cyrusamirabadi** [dtrung98/MusicPlayer#12]
I want to work on the code but as I import it in AS, I get this error:
error: cannot find symbol class MaterialDialog

Can you help me with that?
Best
Cyrus

**Comment by dverdugo85** [comment]
use this 

 implementation 'com.afollestad.material-dialogs:core:0.9.5.0'
    implementation 'com.afollestad.material-dialogs:commons:0.9.5.0'

**Comment by cyrusamirabadi** [comment]
Thanks man
Hope this works

**Comment by dverdugo85** [comment]
@cyrusamirabadi  I try to use the app not work the master!!

**Comment by dverdugo85** [comment]
```
2019-10-14 15:47:20.318 498-25076/? E/audio_hw_extn: audio_extn_perf_lock_acquire: Failed to acquire perf lock, err: -1
2019-10-14 15:47:20.323 498-25076/? E/msm8916_platform: platform_get_snd_device_backend_index: BE DAI Name Table is not present
2019-10-14 15:47:20.323 498-25076/? E/audio_hw_utils: send_app_type_cfg_for_device: Couldn't get the backend index for snd device voice-rec-mic ret=-14
2019-10-14 15:47:20.324 498-25076/? E/ACDB-LOADER: Error: ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE Returned = -19
2019-10-14 15:47:20.384 498-25076/? E/audio_hw_extn: audio_extn_perf_lock_release: Perf lock release error 
2019-10-14 15:47:20.926 643-4675/? E/LightsService: Light requested not available on this device. 2
2019-10-14 15:47:23.183 643-1047/? E/LightsService: Light requested not available on this device. 2
2019-10-14 15:47:23.443 11267-24498/? E/AudioSource: Stop listening is called on already closed AudioSource
2019-10-14 15:47:26.705 25129-25129/? E/android.musicf: Not starting debugger since process cannot load the jdwp agent.
2019-10-14 15:47:27.169 25080-25080/com.ldt.musicr E/com.ldt.musicr: No package ID ff found for ID 0xffffffff.
2019-10-14 15:47:27.794 24971-24989/? E/SQLiteLog: (1) no such column: orientation
2019-10-14 15:47:27.795 24971-24989/? E/DatabaseUtils: Writing exception to parcel
    android.database.sqlite.SQLiteException: no such column: orientation (code 1 SQLITE_ERROR): , while compiling: SELECT orientation FROM album_art WHERE (album_id=?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:939)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:550)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:419)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:335)
        at com.android.providers.media.MediaProvider.query(MediaProvider.java:1668)
        at android.content.ContentProvider.query(ContentProvider.java:1058)
        at android.content.ContentProvider.query(ContentProvider.java:1150)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:731)
2019-10-14 15:47:28.430 25080-25123/com.ldt.musicr E/AndroidRuntime: FATAL EXCEPTION: GLThread 34722
    Process: com.ldt.musicr, PID: 25080
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.ldt.bubblepicker.rendering.java.gltexture.TexturePickerRenderer.initialize(TexturePickerRenderer.kt:84)
        at com.ldt.bubblepicker.rendering.java.gltexture.TexturePickerRenderer.onSurfaceChanged(TexturePickerRenderer.kt:71)
        at com.ldt.bubblepicker.rendering.java.gltexture.GLTextureView$GLThread.guardedRun(GLTextureView.java:1388)
        at com.ldt.bubblepicker.rendering.java.gltexture.GLTextureView$GLThread.run(GLTextureView.java:1123)
2019-10-14 15:47:28.420 24971-24988/? E/SQLiteLog: (1) no such column: orientation
2019-10-14 15:47:28.438 643-15779/? E/LightsService: Light requested not available on this device. 2
2019-10-14 15:47:28.457 24971-24988/? E/DatabaseUtils: Writing exception to parcel
    android.database.sqlite.SQLiteException: no such column: orientation (code 1 SQLITE_ERROR): , while compiling: SELECT orientation FROM album_art WHERE (album_id=?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:939)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:550)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:419)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:335)
        at com.android.providers.media.MediaProvider.query(MediaProvider.java:1668)
        at android.content.ContentProvider.query(ContentProvider.java:1058)
        at android.content.ContentProvider.query(ContentProvider.java:1150)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:731)
2019-10-14 15:47:28.524 643-1047/? E/InputDispatcher: channel '3a4ce71 com.ldt.musicr/com.ldt.musicr.ui.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by dverdugo85** [comment]
Do you have the master that compile the APK
