### ISSUE TITLE
Attempt to invoke virtual method 'int com.ldt.musicr.ui.widget.soundfile.SoundFile.getNumFrames()' on a null object reference

### ISSUE THREAD

**Issue by divy1219** [dtrung98/MusicPlayer#26]
2020-10-16 12:34:23.831 31929-32017/com.ldt.musicr E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.ldt.musicr, PID: 31929
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ldt.musicr.ui.widget.soundfile.SoundFile.getNumFrames()' on a null object reference
        at com.ldt.musicr.ui.widget.avsb.VisualSeekBarParser.parseSoundFileData(VisualSeekBarParser.java:105)
        at com.ldt.musicr.ui.widget.avsb.VisualSeekBarParser.parse(VisualSeekBarParser.java:98)
        at com.ldt.musicr.ui.widget.avsb.VisualSeekBarParser.lambda$parse$0$VisualSeekBarParser(VisualSeekBarParser.java:87)
        at com.ldt.musicr.ui.widget.avsb.-$$Lambda$VisualSeekBarParser$8B63GqoWpmXRFhtljKDgWEqzEJU.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by Mukhtarali6121** [comment]
DID U GET THE SOLUTION
